### ISSUE TITLE
Lesson 8 Defining Your Own Variables not translated to Spanish

### ISSUE THREAD

**Issue by nabadvin** [GDQuest/learn-gdscript-translations#100]
Spanish language is selected in Configure the App > Language, but the first paragraphs of the lesson 8 Defining Your Own Variables are not translated to Spanish.

**Comment by NathanLovato** [comment]
Note for team: this is due to translation source strings being outdated, we need to update them with `msgmerge`

**Comment by NathanLovato** [comment]
This was finally done recently
