### ISSUE TITLE
Can you please fetch latest Weblate translations and merge (2024-10-11)

### ISSUE THREAD

**Issue by yilmazdurmaz** [GDQuest/learn-gdscript-translations#130]
**I'm submitting a...**

- [x] Feature request.

## Feature request ##

Weblate translations are piled up for a long time. Can you please fetch and merge? (at least for Turkish language?)

**Describe the problem you're trying to solve.**

Turkish translations were already full for over a year. At my first sweep, I used informal first-person speak to learners as I thought it would be warmer. Then I decided to change it to a more formal tone. ("you" means both single and plural in English). It took me a long time to finish this because the chapters were long. And I finally finished both that and also proof-reading.

Last year, you told me you were working on a *Godot 4 version of the course, but I guess that project is still baking. So, this course is still a go-to place for newcomers as it is also referenced in the official Godot documentation. (I am also translating them, but it takes way longer compared to here).

Anyways, as it is not automated, it seems it is needed to ask personally to update translations, so here I am.  A pull request is already made by Weblate itself, and waits for you to approve: https://github.com/GDQuest/learn-gdscript-translations/pull/128

Please, fetch the latest if they are not yet already fetched (in case you read really fast) and merge, so that new/updated translations come to life.

**Comment by NathanLovato** [comment]
Sorry for the delay, I was going to Godot conference when you opened this and came back ill. There are a few improvements and fixes going to learn gdscript, and I'll integrate translations after all those are merged, as translations are only updated when a new version of the app comes out.

**Comment by NathanLovato** [comment]
Just merged the weblate contributions, thanks much for your help! I'll prepare a release as soon as possible.
