### ISSUE TITLE
Untranslated/absent strings

### ISSUE THREAD

**Issue by piratesephiroth** [GDQuest/learn-gdscript-translations#18]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Some strings are listed in the .po files but aren't getting translated, while a few others are completely absent.

**What is the expected behavior?**
The application should display translated strings according to what's specified in the .po files.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Here a list of many cases I have spotted:
```

in ui/screens/welcome_screen/WelcomeScreen.tscn:
  untranslated
  "Report an issue"
  "GDScript Learn is a Free and Open-Source app and series to help you learn to "...
  "The app is in [b]beta[/b].\n"...
  "Configure the App"
  "Quit"

  absent:
  "Continue Course", "Start Course"

in ui/components/popups/SettingsPopup.tscn:
  untranslated
  "Configure the app"
  "Language"
  "Framerate cap"
  "Close"

  absent: tooltips

ui/screens/course_outliner/CourseOutliner.tscn
  untranslated
  "Course Index - "
  "Reset Progress"

ui/screens/course_outliner/CourseLessonDetails.gd
  untranslated
  "Start Lesson"
  "Continue Lesson"
  "Open Lesson"

ui/screens/lesson/UIContentBlock.gd
  untranslated
  "Learn More"

ui/screens/lesson/UIBaseQuiz
  untranslated
  "Skip"
  "Submit"

ui/screens/lesson/quizzes/UIQuizChoice.gd
  untranslated
  "(select all that apply)"

ui/screens/practice/PracticeInfoPanel.tscn
  untranslated
  "Goals"
  "Hints"

ui/components/CodeEditor.tscn:239 ui/components/OutputConsole.tscn
  untranslated
  "Output"

course/glossary.csv
  nothing seems to get translated
```

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment]
Thanks, please let us know whenever you encounter those strings, you can open new issues when that happens. It can be a synchronization problem, or yeah strings that don't get found by the extraction script. We'll look into it

**Comment by NathanLovato** [comment]
This should be fixed as we synchronized the translation strings some time ago
